//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetDBEntities : DbContext
    {
        public PetDBEntities()
            : base("name=PetDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pet> Pets { get; set; }
        public virtual DbSet<Pet_Type> Pet_Type { get; set; }
        public virtual DbSet<Sale_Line_Pet> Sale_Line_Pet { get; set; }
        public virtual DbSet<Sale_Pet> Sale_Pet { get; set; }
    }
}
