//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_Pet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale_Pet()
        {
            this.Sale_Line_Pet = new HashSet<Sale_Line_Pet>();
        }
    
        public int Sale_ID { get; set; }
        public Nullable<double> Sale_Amount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale_Line_Pet> Sale_Line_Pet { get; set; }
    }
}
